#pragma once
#include <Arduino.h>
// Interface languages of the screens. English and Russian are written in the code as
// t("English","Русский"); the other languages come from include/I18nTable.h, generated by
// tools/i18n.py from i18n/firmware/<lang>.json. The language number is stored in NVS
// ("lang"), so the order below never changes; new languages go to the end.
enum Lang:uint8_t {LangEn,LangRu,LangUk,LangEs,LangPt,LangFr,LangDe,LangIt,LangPl,LangTr,LangZh,LangJa,LangKo,LangAr,LangId,LangCount};
extern const char* const langCodes[LangCount]; // "en", "ru", ...
extern const char* const langNames[LangCount]; // each in its own language
int langFromCode(const String& code); // -1 when unknown
// The text in the interface language; a string without a translation shows English.
const char* tr(const char* en,const char* ru);
// "5 games": the number and the noun form its language needs. English and Russian are the arguments
// (number, space, form); translations place the number with {n} or leave it out.
String plural(unsigned n,const char* one,const char* many,const char* ru1,const char* ru2,const char* ru5);
// The language the site installer chose ("" when the image was not installed from the site).
String installLanguage();

// Drawing text in every language.
// Arabic is joined (presentation forms) and put in visual order; other text comes back unchanged.
String visualText(const String& logical);
// Fonts tried after `font` for a glyph it lacks: Latin-1, Latin Extended, then the CJK and Arabic subsets
// (include/I18nFonts.h), the interface language's script first. Null-terminated.
const uint8_t* const* fallbackFonts(const uint8_t* font);
bool fontHasGlyph(const uint8_t* font,uint16_t cp);
// Two cells for CJK and other wide glyphs, one otherwise: column counting on the 128x64 screens.
uint8_t glyphCells(uint32_t cp);
uint32_t utf8Next(const String& s,unsigned& i); // the codepoint at i; i moves past it
