#pragma once
#include <Arduino.h>
#include <type_traits>
// Interface languages of the screens. English and Russian are written in the code as
// t("English","Русский"); the other languages come from include/I18nTable.h, generated by
// tools/i18n.py from i18n/firmware/<lang>.json. The language number is stored in NVS
// ("lang"), so the order below never changes; new languages go to the end.
enum Lang:uint8_t {LangEn,LangRu,LangUk,LangEs,LangPt,LangFr,LangDe,LangIt,LangPl,LangTr,LangZh,LangJa,LangKo,LangAr,LangId,LangCount};
extern const char* const langCodes[LangCount]; // "en", "ru", ...
extern const char* const langNames[LangCount]; // each in its own language
int langFromCode(const String& code); // -1 when unknown
// Whether this image has the language. ESP32 images have all; an nRF52 image (1 MB flash) has English
// and Russian, or English and the one language it is built for (without Russian, MM_NO_RU) (MM_LANG_EXTRA, its number; tools/pio_lang.py, the site
// installs the image of the chosen language).
bool langAvailable(uint8_t l);
uint8_t langStep(uint8_t l,int dir); // the next (dir>0) or previous available language
// The text in the interface language; a string without a translation shows English. tr("English","Русский")
// is a macro: the key of the translation (FNV-1a over English, 0x1f and Russian, as tools/i18n.py) is computed
// by the compiler, so an image without Russian (MM_NO_RU: the nRF52 images of the other languages) does not
// carry the Russian strings. Pairs read from tables go through trPair().
constexpr uint32_t i18nFnv(const char* s,uint32_t h){while(*s)h=(h^uint8_t(*s++))*0x01000193u;return h;}
constexpr uint32_t i18nKey(const char* en,const char* ru){return i18nFnv(ru,(i18nFnv(en,0x811c9dc5u)^0x1fu)*0x01000193u);}
const char* trKey(const char* en,const char* ru,uint32_t key); // ru: nullptr in an image without Russian
inline const char* trPair(const char* en,const char* ru){return trKey(en,ru,i18nKey(en,ru));}
#if defined(MM_NO_RU)
#define MM_RU(s) nullptr
#else
#define MM_RU(s) s
#endif
#define tr(en,ru) trKey(en,MM_RU(ru),std::integral_constant<uint32_t,i18nKey(en,ru)>::value)
// "5 games": the number and the noun form its language needs. English and Russian are the arguments
// (number, space, form); translations place the number with {n} or leave it out.
String plural(unsigned n,const char* one,const char* many,const char* ru1,const char* ru2,const char* ru5);
// The language the site installer chose ("" when the image was not installed from the site).
String installLanguage();

// Drawing text in every language.
// Arabic is joined (presentation forms) and put in visual order; other text comes back unchanged.
String visualText(const String& logical);
// Fonts tried after `font` for a glyph it lacks: Latin-1, Latin Extended, then the CJK and Arabic subsets
// (include/I18nFonts.h), the interface language's script first. Null-terminated.
const uint8_t* const* fallbackFonts(const uint8_t* font);
bool fontHasGlyph(const uint8_t* font,uint16_t cp);
// Two cells for CJK and other wide glyphs, one otherwise: column counting on the 128x64 screens.
uint8_t glyphCells(uint32_t cp);
uint32_t utf8Next(const String& s,unsigned& i); // the codepoint at i; i moves past it
