#!/usr/bin/env python3
"""The mesh pet's species: pixel art and colours -> include/PetSprites.h.

python3 tools/pet_sprites.py            writes the header
python3 tools/pet_sprites.py --sheet OUT.png   also draws every species, young and grown, with a face

Art: 16x16, '.' empty, 'o' outline, 'b' body, 'a' accent (belly, spots, ears, stripes; the accent in the
top four rows lights up when a packet arrives). Each sprite has a face: the row of its 2x2 eyes, the left
and right eye columns, the mouth row (the mouth is at columns 7-8) and the cheek row (cheeks at 3 and 12).
The header packs a row into 32 bits, two bits a pixel, so 15 species with two looks take about 2 KB.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# name, body RGB, accent RGB, young (art, face), grown (art, face); face = (eye, left, right, mouth, cheek)
SPECIES = [
 ("Pinglet", 0x5fd3b0, 0xfff4dc, ("""
................
.......oo.......
......oaao......
.......oo.......
.....oooooo.....
....obbbbbbo....
...obbbbbbbbo...
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbaaaabbbo..
...obaaaaaabo...
....oooooooo....
....oo....oo....
................""", (7, 5, 9, 10, 9)), ("""
......oooo......
......oaao......
.o.....oo.....o.
.oo....oo....oo.
.oboooooooooobo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
oobbbbbbbbbbbboo
obobbbbbbbbbbobo
oobbbbaaaabbbboo
.obbbaaaaaabbbo.
.obbbaaaaaabbbo.
..oooooooooooo..
...ooo....ooo...""", (6, 4, 10, 9, 8))),
 ("Bytecat", 0xffa36c, 0xffd0dc, ("""
................
................
................
...o........o...
...oo......oo...
...oao....oao...
...oboooooobo...
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbaaaabbo...
...obaaaaaabo...
....oooooooo....
....oo....oo....
................""", (8, 5, 9, 10, 10)), ("""
................
..o..........o..
..oo........oo..
..oao......oao..
..oaao....oaao..
..oboooooooobo..
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
oobbbbbbbbbbbboo
.obbbbbbbbbbbbo.
oobbbbbbbbbbbboo
..obbbaaaabbbo..
..obbaaaaaabbo..
..obbbbbbbbbbo..
..ooo..oo..ooo..""", (7, 4, 10, 9, 10))),
 ("Lorafox", 0xff7a3d, 0xfff4dc, ("""
................
................
..o..........o..
..oo........oo..
..obo......obo..
..obboooooobbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbaaaabbo...
...oaaaaaaaao...
....oaaaaaao....
.....oaaaao.....
......oooo......
................
................""", (7, 5, 9, 10, 8)), ("""
.o.........o....
.oo.......oo....
.obo.....obo....
.obbooooobbo....
.obbbbbbbbbo....
.obbbbbbbbbo....
.obbbbbbbbbo..oo
..oaabbbaao..oao
..oaaaaaaao.obao
...oaaaaao..obbo
..obbbbbbbooobbo
..obbbaaabbbbbo.
..obbaaaaabbbo..
..obbaaaaabbo...
..oobbbbbboo....
...oo.....oo....""", (4, 3, 7, 7, 6))),
 ("Hootnode", 0xa0785a, 0xf2e2c4, ("""
................
................
................
...oo......oo...
...obo....obo...
...obbooooobbo..
..obaaabbaaabo..
..obaaabbaaabo..
..obaaabbaaabo..
..obbbboobbbbo..
..obbbbbbbbbbo..
..obbaaaaaabbo..
...obaaaaaabo...
....oooooooo....
.....o....o.....
................""", (7, 4, 10, 10, 11)), ("""
..oo........oo..
..obo......obo..
..obbooooooobbo.
.obaaaabbaaaabo.
.obaaaabbaaaabo.
.obaaaabbaaaabo.
.obaaaabbaaaabo.
.obbbbboobbbbbo.
oobbbbbbbbbbbboo
obbbbaaaaaabbbbo
obbbaaaaaaaabbbo
oobbaaaaaaaabboo
.obbaaaaaaaabbo.
..obbbbbbbbbbo..
...oooooooooo...
....o.o..o.o....""", (4, 3, 11, 8, 9))),
 ("Sparkdrake", 0x6cc24a, 0xf2c94c, ("""
................
................
................
......o..o......
.....oaooao.....
....oooooooo....
...obbbbbbbbo...
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbaaaabbbo..
...obaaaaaabo...
...obbaaaabbo...
....oooooooo....
....oo....oo....
................""", (8, 5, 9, 10, 9)), ("""
.......oo.......
......oaao......
.....oaaaao.....
....oooooooo....
o..obbbbbbbbo..o
oo.obbbbbbbbo.oo
oaoobbbbbbbboaoo
oaaobbbbbbbboaao
oaaobbbbbbbboaao
.oaobbaaaabboao.
..oobaaaaaaboo..
...obaaaaaabo...
...obbaaaabbo...
...obbbbbbbbo...
...oooooooooo...
...oo......oo...""", (6, 5, 9, 8, 7))),
 ("Bunbit", 0xe9e4f2, 0xff9ec4, ("""
....oo....oo....
...oaao..oaao...
...oaao..oaao...
...oaao..oaao...
...oboo..oobo...
....oooooooo....
...obbbbbbbbo...
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbbbbbbbo...
....oooooooo....
....oo....oo....
................""", (8, 5, 9, 10, 10)), ("""
...oo......oo...
..oaao....oaao..
..oaao....oaao..
..oaao....oaao..
..oaao....oaao..
..obbooooooobbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
oobbbbaaaabbbboo
.obbbaaaaaabbbo.
.obbbaaaaaabbbo.
..obbbbbbbbbbo..
..oooooooooooo..
..oooo....oooo..""", (7, 4, 10, 9, 9))),
 ("Octomesh", 0xb48cff, 0xf3d9ff, ("""
................
................
................
.....oooooo.....
....obbbbbbo....
...obbaabbbbo...
..obbaabbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbbbbbbbo...
...obobobobbo...
..obo.obo.obo...
..oo..oo..oo....
................
................""", (7, 5, 9, 9, 9)), ("""
.....oooooo.....
....obbbbbbo....
...obbaabbbbo...
..obbaabbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbbbbbbbo...
..oboboobobobo..
.obo.obo.obo.bo.
.obo.obo.obo.bo.
obo.obo..obo.obo
oo..oo....oo..oo
................
................""", (5, 5, 9, 7, 7))),
 ("Boo", 0xdfe9f5, 0x9fb6d6, ("""
................
................
................
.....oooooo.....
....obbbbbbo....
...obbbbbbbbo...
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obaobbobboao..
..oo.oo.oo.oo...
................
................""", (7, 5, 9, 9, 9)), ("""
.....oooooo.....
...oobbbbbboo...
..obbbbbbbbbbo..
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
oobbbbbbbbbbbboo
obobbbbbbbbbbobo
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obaobbaobbaobo.
.oo.oo.oo.oo.oo.
................""", (5, 4, 10, 8, 7))),
 ("Robo", 0x9aa7b4, 0x52c8e0, ("""
................
.......oo.......
......oaao......
.......oo.......
...oooooooooo...
...obbbbbbbbo...
..ooaaaaaaaaoo..
..ooaaaaaaaaoo..
...oaaaaaaaao...
...obbbbbbbbo...
...oooooooooo...
....obbbbbbo....
....oboaaobo....
....oooooooo....
....oo....oo....
................""", (6, 5, 9, 8, 9)), ("""
.......oo.......
......oaao......
.......oo.......
..oooooooooooo..
..obbbbbbbbbbo..
.ooaaaaaaaaaaoo.
.ooaaaaaaaaaaoo.
..oaaaaaaaaaao..
..obbbbbbbbbbo..
..oooooooooooo..
oo.obbbbbbbbo.oo
obooboaaaobooobo
oo.obbbbbbbbo.oo
...obbbbbbbbo...
...oooooooooo...
...ooo....ooo...""", (5, 4, 10, 7, 4))),
 ("Ribbit", 0x9ad35a, 0xf6f3c8, ("""
................
................
................
................
...oooo..oooo...
..obbbbooaabbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbaaaaaabbbo.
..obaaaaaaaabo..
...oooooooooo...
..oo........oo..
................
................""", (5, 3, 10, 8, 9)), ("""
................
...oooo..oooo...
..obbbbooaabbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
obbbbbbbbbbbbbbo
obbbaaaaaaaabbbo
obbaaaaaaaaaabbo
.obaaaaaaaaaabo.
.obbaaaaaaaabbo.
..obbbbbbbbbbo..
.ooooooooooooo..
oo..oo....oo..oo
................""", (2, 3, 10, 6, 7))),
 ("Pengu", 0x34405a, 0xf5f7fa, ("""
................
................
................
.....oooooo.....
....obbbbbbo....
...obaabbaabo...
..obaaaaaaaabo..
..obaaaaaaaabo..
..obbaaaaaabbo..
..obbaaaaaabbo..
..obbaaaaaabbo..
...obaaaaaabo...
....oooooooo....
....oo....oo....
................
................""", (6, 5, 9, 8, 8)), ("""
.....oooooo.....
....obbbbbbo....
...obbbbbbbbo...
..obaaabbaaabo..
..obaaaaaaaabo..
..obaaaaaaaabo..
.oobbaaaaaabboo.
obobbaaaaaabbobo
obobbaaaaaabbobo
.oobbaaaaaabboo.
..obbaaaaaabbo..
..obbaaaaaabbo..
...obaaaaaabo...
....oooooooo....
...ooo....ooo...
................""", (4, 4, 10, 6, 6))),
 ("Shroom", 0xe5564d, 0xfff4dc, ("""
................
................
................
.....oooooo.....
...oobbaabboo...
..obbaabbbabbo..
..obbbbbbbbbbo..
.oooooooooooooo.
....oaaaaaao....
....oaaaaaao....
....oaaaaaao....
....oaaaaaao....
.....oooooo.....
................
................
................""", (8, 5, 9, 10, 10)), ("""
....oooooooo....
..oobbaabbbboo..
.obbbaabbbaabbo.
obbbbbbbbbaabbbo
obaabbbbbbbbbbbo
obaabbbaabbbbbbo
oooooooooooooooo
....oaaaaaao....
....oaaaaaao....
....oaaaaaao....
...ooaaaaaaoo...
..oaoaaaaaaoao..
...ooaaaaaaoo...
....oaaaaaao....
....oooooooo....
................""", (8, 5, 9, 10, 99))),
 ("Jelly", 0x52c8e0, 0xc8f4ff, ("""
................
................
................
................
................
.......oo.......
.....oobboo.....
....obaabbbo....
...obaabbbbbo...
..obbbbbbbbbbo..
..obbbbbbbbbbo..
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
..oobboooobboo..
....oo....oo....
................""", (9, 5, 9, 11, 11)), ("""
................
................
.......oo.......
.....oobboo.....
....obaabbbo....
...obaabbbbbo...
..obbbbbbbbbbo..
..obbbbbbbbbbo..
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
obbbbbbbbbbbbbbo
obbbbbbbbbbbbbbo
obbbbbbbbbbbbbbo
.obboobbbboobbo.
..oo.obo.obo.oo.
.....oo...oo....""", (7, 4, 10, 10, 9))),
 ("Buzz", 0xf2c94c, 0x2c2c34, ("""
................
................
......o..o......
.......oo.......
..oo.oooooo.oo..
.obboobbbbbobbo.
.obbobbbbbbbobo.
..oobbbbbbbboo..
...obbbbbbbbo...
...oaaaaaaaao...
...obbbbbbbbo...
...oaaaaaaaao...
....obbbbbbo....
.....oooooo.....
.......oo.......
................""", (6, 5, 9, 8, 8)), ("""
.....o....o.....
......o..o......
..oo...oo...oo..
.obbo.oooo.obbo.
.obbbobbbbobbbo.
..obobbbbbbobo..
...obbbbbbbbo...
..obbbbbbbbbbo..
..oaaaaaaaaaao..
..obbbbbbbbbbo..
..oaaaaaaaaaao..
..obbbbbbbbbbo..
...oaaaaaaaao...
....obbbbbbo....
.....oooooo.....
.......oo.......""", (5, 5, 9, 7, 7))),
 ("Axolotl", 0xff9ec4, 0xe5568a, ("""
................
................
................
................
oo.oooooooooo.oo
oaoobbbbbbbbooao
.aoobbbbbbbbooa.
oaobbbbbbbbbboao
.oobbbbbbbbbboo.
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbbbbbbbo...
....oooooooo....
....oo....oo....
................
................""", (7, 5, 9, 9, 9)), ("""
................
oo.oooooooooo.oo
oaoobbbbbbbbooao
.aoobbbbbbbbooa.
oaobbbbbbbbbboao
.oobbbbbbbbbboo.
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbbbbbbbo...
..oobbbbbbbboo..
.obobbbbbbbbobo.
.oobbbbbbbbbboo.
...obbbbbbbbo...
...obbbbbbbbooo.
...oooooooooooao
...oo....oo..oo.""", (4, 5, 9, 7, 6))),
]
INK = {'.': 0, 'o': 1, 'b': 2, 'a': 3}


def rows(art):
    r = art.strip('\n').split('\n')
    return r


def check():
    errors = []
    for name, body, accent, *looks in SPECIES:
        for look, (art, face) in zip(('young', 'grown'), looks):
            r = rows(art)
            if len(r) != 16 or any(len(x) != 16 for x in r):
                errors.append(f'{name} {look}: not 16x16 ({len(r)} rows, widths {[len(x) for x in r]})')
                continue
            if any(c not in INK for x in r for c in x):
                errors.append(f'{name} {look}: unknown character')
            eye, left, right, mouth, cheek = face
            for x in (left, left + 1, right, right + 1):
                for y in (eye, eye + 1):
                    if r[y][x] not in 'ba':
                        errors.append(f'{name} {look}: eye at {x},{y} on {r[y][x]!r}')
            for x in (7, 8):
                if r[mouth][x] not in 'ba':
                    errors.append(f'{name} {look}: mouth at {x},{mouth} on {r[mouth][x]!r}')
    return errors


def header():
    out = ['// Generated by tools/pet_sprites.py: the mesh pet species, their colours and pixel art (16x16, two',
           '// bits a pixel: 0 empty, 1 outline, 2 body, 3 accent; bit 2k of a row is column k). Do not edit.',
           '// The colours are constants (the T114 palette uses them); the drawings are defined once, in Pet.cpp.',
           '#pragma once', '#include <stdint.h>', 'namespace pet {',
           f'constexpr unsigned Species={len(SPECIES)};',
           'constexpr uint32_t bodies[Species]={' + ','.join(f'0x{b:06x}' for _, b, *_ in SPECIES) + '};',
           'constexpr uint32_t accents[Species]={' + ','.join(f'0x{a:06x}' for _, _, a, *_ in SPECIES) + '};',
           'struct Look{uint32_t rows[16];int8_t eye,left,right,mouth,cheek;};',
           'struct Kind{const char* name;Look young,grown;};',
           'extern const Kind kinds[Species];',
           '#if defined(PET_SPRITES_DEFINE)',
           'const Kind kinds[Species]={']
    for name, body, accent, *looks in SPECIES:
        parts = []
        for art, face in looks:
            words = []
            for row in rows(art):
                v = 0
                for k, c in enumerate(row):
                    v |= INK[c] << (2 * k)
                words.append(f'0x{v:08x}')
            parts.append('{{' + ','.join(words) + '},' + ','.join(str(x) for x in face) + '}')
        out.append(f' {{"{name}",\n  ' + ',\n  '.join(parts) + '},')
    out += ['};', '#endif', '}', '']
    return '\n'.join(out)


def sheet(path):
    from PIL import Image, ImageDraw
    S, pad = 8, 10
    cols = 5
    rows_n = (len(SPECIES) + cols - 1) // cols
    cw, ch = 2 * 16 * S + 3 * pad, 16 * S + 2 * pad + 20
    im = Image.new('RGB', (cols * cw, rows_n * ch), (8, 12, 17))
    d = ImageDraw.Draw(im)

    def rgb(v):
        return ((v >> 16) & 255, (v >> 8) & 255, v & 255)

    for i, (name, body, accent, *looks) in enumerate(SPECIES):
        cx, cy = (i % cols) * cw, (i // cols) * ch
        d.rounded_rectangle((cx + 4, cy + 4, cx + cw - 4, cy + ch - 4), 10, fill=(19, 26, 34))
        d.text((cx + pad + 2, cy + 6), name, fill=(228, 233, 238))
        b = rgb(body)
        outline = tuple(int(c * .32) for c in b)
        for j, (art, face) in enumerate(looks):
            ox, oy = cx + pad + j * (16 * S + pad), cy + 20
            grid = [list(r) for r in rows(art)]
            for y, r in enumerate(grid):
                for x, c in enumerate(r):
                    col = {'o': outline, 'b': b, 'a': rgb(accent)}.get(c)
                    if col:
                        d.rectangle((ox + x * S, oy + y * S, ox + x * S + S - 1, oy + y * S + S - 1), fill=col)
            eye, left, right, mouth, cheek = face
            for x in (left, left + 1, right, right + 1):
                for y in (eye, eye + 1):
                    d.rectangle((ox + x * S, oy + y * S, ox + x * S + S - 1, oy + y * S + S - 1), fill=(16, 20, 24))
            for x, y in ((6, mouth), (9, mouth), (7, mouth + 1), (8, mouth + 1)):
                d.rectangle((ox + x * S, oy + y * S, ox + x * S + S - 1, oy + y * S + S - 1), fill=(16, 20, 24))
            if 0 <= cheek < 16:
                for x in (3, 12):
                    if grid[cheek][x] in 'ba':
                        d.rectangle((ox + x * S, oy + cheek * S, ox + x * S + S - 1, oy + cheek * S + S - 1), fill=(244, 114, 182))
    im.save(path)


if __name__ == '__main__':
    errors = check()
    for e in errors:
        print(e)
    if errors:
        raise SystemExit(1)
    (ROOT / 'include/PetSprites.h').write_text(header())
    if len(sys.argv) > 2 and sys.argv[1] == '--sheet':
        sheet(sys.argv[2])
    print(f'include/PetSprites.h: {len(SPECIES)} species')
