#include "App.h"
#include "Hardware.h"
#include "MeshRadio.h"
#include "Maps.h"
#include "Navigation.h"
#include <Preferences.h>
#include <Mm1Packet.h>
#include <time.h>
#include <math.h>
namespace {
enum Page {Home,Threads,Chat,Map,Nodes,Sensors,Settings,Radio,Display,Network,Diagnostics,Help,Library};
const char* pageNames[]={"home","threads","chat","map","nodes","sensors","settings","radio","display","network","diagnostics","help","library"};
Page page=Home,chatReturn=Threads;
uint32_t lastDraw=0,lastInput=0,toastAt=0;String toast,eventSeen;
int selected=0,chatOffset=0;
uint64_t recipient=meshmesh::Broadcast;
String composer,edit;bool editing=false,dirty=true,locked=false,wakeOnly=false,keyboardRussian=true;
Config draft;
struct ComposerDraft{uint64_t recipient=0;String text;uint32_t touched=0;} drafts[16];
DynamicJsonDocument library(8192);
uint64_t conversations[65];unsigned conversationCount=1;
const uint16_t bg=0x0862,panel=0x10c5,accent=0x67db,muted=0x9d36,green=0x67d1,red=0xfacb,white=0xef7d;
String t(const char* en,const char* ru){return config.russian?ru:en;}
String flag(bool v){return v?t("On","Вкл"):t("Off","Выкл");}
String clip(const String& s,unsigned n){unsigned i=0,k=0;while(i<s.length()&&k<n){uint8_t c=s[i];i+=c<128?1:(c&0xe0)==0xc0?2:(c&0xf0)==0xe0?3:4;k++;}if(i>=s.length())return s;i=k=0;while(i<s.length()&&k+3<n){uint8_t c=s[i];i+=c<128?1:(c&0xe0)==0xc0?2:(c&0xf0)==0xe0?3:4;k++;}return s.substring(0,i)+"...";}
void notice(String value){toast=value;toastAt=millis();dirty=true;}
void label(int x,int y,const String& s,uint16_t color=white){hardware.text(x,y,s,color);}
void row(int y,const String& title,const String& detail,bool focus){auto& c=*hardware.canvas;if(focus)c.fillRoundRect(8,y-15,304,34,6,0x1a69);label(16,y,clip(title,45),focus?accent:white);if(detail.length())label(16,y+14,clip(detail,46),muted);if(focus)label(296,y,">",accent);}
bool belongs(const ChatMessage& m,uint64_t id){return id==meshmesh::Broadcast?m.destination==id:(m.outgoing?m.destination==id:m.source==id&&(m.destination==meshRadio.nodeId||m.protocol==1));}
void threads(){conversationCount=1;conversations[0]=meshmesh::Broadcast;for(int i=int(meshRadio.historyCount)-1;i>=0;i--){auto& m=meshRadio.history[i];uint64_t id=m.outgoing?m.destination:m.source;if(m.destination==meshmesh::Broadcast)id=meshmesh::Broadcast;if(id==meshmesh::Broadcast)continue;bool found=false;for(unsigned j=1;j<conversationCount;j++)if(conversations[j]==id)found=true;if(!found&&conversationCount<65)conversations[conversationCount++]=id;}}
String nameOf(uint64_t id){if(id==meshmesh::Broadcast)return t("Public · MeshCore","Public · MeshCore");for(auto& p:meshRadio.peers)if(p.id==id)return p.name;for(int i=meshRadio.historyCount-1;i>=0;i--)if(meshRadio.history[i].source==id)return meshRadio.history[i].name;return meshRadio.idText(id);}
String readKey(uint64_t id){if(id==meshmesh::Broadcast)return "all";char b[15]={};unsigned n=0;do{b[n++]="0123456789abcdefghijklmnopqrstuvwxyz"[id%36];id/=36;}while(id);String key="r";while(n)key+=b[--n];return key;}
uint32_t readAt(uint64_t id){Preferences p;if(!p.begin("meshmesh-ui",true))return 0;uint32_t v=p.getUInt(readKey(id).c_str(),0);p.end();return v;}
unsigned unread(uint64_t id){uint32_t at=readAt(id);unsigned n=0;for(unsigned i=0;i<meshRadio.historyCount;i++){auto& m=meshRadio.history[i];if(belongs(m,id)&&!m.outgoing&&m.timestamp>at)n++;}return n;}
void markRead(){uint32_t at=0;for(unsigned i=0;i<meshRadio.historyCount;i++){auto& m=meshRadio.history[i];if(belongs(m,recipient)&&!m.outgoing)at=max(at,m.timestamp);}if(at>readAt(recipient)){Preferences p;if(p.begin("meshmesh-ui",false)){p.putUInt(readKey(recipient).c_str(),at);p.end();}}}
void rememberComposer(){int chosen=-1;for(int i=0;i<16;i++)if(drafts[i].recipient==recipient){chosen=i;break;}if(chosen<0)for(int i=0;i<16;i++)if(!drafts[i].recipient){chosen=i;break;}if(chosen<0){chosen=0;for(int i=1;i<16;i++)if(drafts[i].touched<drafts[chosen].touched)chosen=i;}drafts[chosen].recipient=recipient;drafts[chosen].text=composer;drafts[chosen].touched=millis();}
String restoredComposer(){for(auto& d:drafts)if(d.recipient==recipient)return d.text;return "";}
void change(Page next){if(page==Chat&&next!=Chat)rememberComposer();page=next;selected=0;chatOffset=0;editing=false;dirty=true;if(next==Radio||next==Display)draft=config;if(next==Threads)threads();if(next==Chat){composer=restoredComposer();markRead();}if(next==Library)deserializeJson(library,maps.areas());}
String clockText(){time_t now=time(nullptr);if(now<1700000000)return "--:--";now+=config.utcOffset*60;tm* v=gmtime(&now);char b[6];snprintf(b,sizeof b,"%02d:%02d",v->tm_hour,v->tm_min);return b;}
String timeText(uint32_t now){if(now<1700000000)return "";time_t n=now+config.utcOffset*60;tm* v=gmtime(&n);char b[6];snprintf(b,sizeof b,"%02d:%02d",v->tm_hour,v->tm_min);return b;}
const char* stateEn[]={"Received","Queued","Sent","Delivered","Unconfirmed"};const char* stateRu[]={"Получено","В очереди","Отправлено","Доставлено","Не подтверждено"};
String state(const ChatMessage& m){return (config.russian?String(stateRu[m.status]):String(stateEn[m.status]))+(m.protocol==1?" · MM/1":"");}
String keyboard(int key){String ch=String(char(key));if(keyboardRussian){const char* symbols="{}:\"<>~@#$^&?/|";const char* mapped[]={"Х","Ъ","Ж","Э","Б","Ю","Ё","\"","№",";",":","?",",",".","/"};if(const char* symbol=strchr(symbols,key))return mapped[symbol-symbols];const char* letters="qwertyuiop[]asdfghjkl;'zxcvbnm,.`";const char* lo[]={"й","ц","у","к","е","н","г","ш","щ","з","х","ъ","ф","ы","в","а","п","р","о","л","д","ж","э","я","ч","с","м","и","т","ь","б","ю","ё"};const char* up[]={"Й","Ц","У","К","Е","Н","Г","Ш","Щ","З","Х","Ъ","Ф","Ы","В","А","П","Р","О","Л","Д","Ж","Э","Я","Ч","С","М","И","Т","Ь","Б","Ю","Ё"};const char* f=strchr(letters,tolower(key));if(f)ch=key>='A'&&key<='Z'?up[f-letters]:lo[f-letters];}return ch;}
unsigned lines(const String& value,String* output,unsigned cols,unsigned maxRows){String row;unsigned count=0,columns=0;for(unsigned i=0;i<value.length();){uint8_t c=value[i];unsigned n=c<128?1:(c&0xe0)==0xc0?2:(c&0xf0)==0xe0?3:4;if(c=='\n'||columns==cols){if(count<maxRows)output[count++]=row;else break;row="";columns=0;if(c=='\n'){i++;continue;}}row+=value.substring(i,i+n);i+=n;columns++;}if(count<maxRows)output[count++]=row;return count;}
void footer(const String& value){hardware.canvas->fillRect(0,222,320,18,panel);label(8,235,clip(value,49),muted);}
String setting(int i){if(page==Radio){switch(i){case 0:return t("Frequency","Частота")+": "+String(draft.frequency,3)+" MHz";case 1:return t("Bandwidth","Полоса")+": "+String(draft.bandwidth,1)+" kHz";case 2:return "SF: "+String(draft.sf);case 3:return "CR: 4/"+String(draft.cr);case 4:return t("Power","Мощность")+": "+String(draft.power)+" dBm";case 5:return t("Relay limit","Предел пересылок")+": "+String(draft.hops);case 6:return t("Relay","Ретрансляция")+": "+flag(draft.relay);case 7:return t("Save changes","Сохранить изменения");}}else {switch(i){case 0:return t("Name","Имя")+": "+String(draft.name);case 1:return t("Language","Язык")+": "+(draft.russian?"Русский":"English");case 2:return t("Brightness","Яркость")+": "+String(draft.brightness);case 3:return t("Sounds","Звуки")+": "+flag(draft.sound);case 4:return t("Auto lock","Автоблокировка")+": "+(draft.autoLock?String(draft.autoLock)+t(" sec"," сек"):t("Off","Выкл"));case 5:return t("Dim screen","Гасить экран")+": "+(draft.dimAfter?String(draft.dimAfter)+t(" sec"," сек"):t("Off","Выкл"));case 6:return "GPS: "+flag(draft.gps);case 7:return "UTC: "+String(draft.utcOffset/60.f,2);case 8:return t("Save changes","Сохранить изменения");}}return "";}
void alter(int dir){if(page==Radio){switch(selected){case 0:draft.frequency=constrain(roundf((draft.frequency+dir*.001f)*1000)/1000,863.f,870.f);break;case 1:{float bw[]={62.5,125,250,500};int i=0;while(i<3&&draft.bandwidth!=bw[i])i++;draft.bandwidth=bw[(i+dir+4)%4];break;}case 2:draft.sf=constrain(int(draft.sf)+dir,7,12);break;case 3:draft.cr=constrain(int(draft.cr)+dir,5,8);break;case 4:draft.power=constrain(int(draft.power)+dir,0,22);break;case 5:draft.hops=constrain(int(draft.hops)+dir,0,7);break;case 6:draft.relay=!draft.relay;break;}}else switch(selected){case 1:draft.russian=!draft.russian;break;case 2:draft.brightness=constrain(int(draft.brightness)+dir*15,10,255);break;case 3:draft.sound=!draft.sound;break;case 4:draft.autoLock=constrain(int(draft.autoLock)+dir*30,0,600);break;case 5:draft.dimAfter=constrain(int(draft.dimAfter)+dir*10,0,600);break;case 6:draft.gps=!draft.gps;break;case 7:draft.utcOffset=constrain(int(draft.utcOffset)+dir*15,-720,840);break;}dirty=true;}
void saveDraft(){StaticJsonDocument<768>d;deserializeJson(d,configJson());if(page==Radio){d["frequency"]=draft.frequency;d["bandwidth"]=draft.bandwidth;d["sf"]=int(draft.sf);d["cr"]=int(draft.cr);d["power"]=int(draft.power);d["hops"]=int(draft.hops);d["relay"]=draft.relay;}else{d["name"]=draft.name;d["russian"]=draft.russian;d["brightness"]=int(draft.brightness);d["sound"]=draft.sound;d["gps"]=draft.gps;d["auto_lock"]=int(draft.autoLock);d["dim_after"]=int(draft.dimAfter);d["utc_offset"]=int(draft.utcOffset);}String reply=applySettings(d.as<JsonObjectConst>());notice(reply.startsWith("OK")?t("Settings saved","Настройки сохранены"):reply);if(reply.startsWith("OK"))change(Settings);}
void drawChat(){auto& c=*hardware.canvas;label(12,46,clip(nameOf(recipient),34),accent);label(265,46,keyboardRussian?"RU":"EN",muted);
 int indices[64],count=0;for(unsigned i=0;i<meshRadio.historyCount;i++)if(belongs(meshRadio.history[i],recipient))indices[count++]=i;
 int end=max(0,count-chatOffset),bottom=178;
 for(int j=end-1;j>=0;j--){auto& m=meshRadio.history[indices[j]];String textRows[8];unsigned n=lines(m.text,textRows,39,8);int extra=m.outgoing?43:27;int height=extra+n*14;if(bottom-height<52) {if(j==end-1){height=bottom-52;n=min(n,unsigned((height-extra)/14));}else break;}
 int x=m.outgoing?42:8,y=bottom-height;c.fillRoundRect(x,y,270,height-4,7,m.outgoing?0x1a8a:panel);label(x+8,y+14,clip(m.outgoing?t("You","Вы"):String(m.name),24),m.outgoing?accent:green);label(x+220,y+14,timeText(m.timestamp),muted);for(unsigned k=0;k<n;k++)label(x+8,y+29+k*14,textRows[k]);if(m.outgoing)label(x+8,bottom-9,state(m),m.status==ChatMessage::Failed?red:muted);bottom=y-4;}
 if(!count){label(20,94,t("Start a conversation","Начните разговор"),muted);label(20,118,t("Type, then press OK","Введите текст и нажмите OK"),muted);}
 c.fillRoundRect(8,182,304,36,6,0x18e6);String rows[5];unsigned n=lines(composer,rows,44,5);if(composer.length()){unsigned first=n>2?n-2:0;for(unsigned i=first;i<n;i++)label(14,197+(i-first)*14,rows[i],accent);}else label(14,203,t("Message...","Сообщение..."),muted);
 footer(t("OK: send  @: language  ","OK: отправить  @: язык  ")+String(composer.length())+"/"+String(meshRadio.messageLimit(recipient)));}
void drawMap(){auto& c=*hardware.canvas;maps.draw(0,28,320,174);
 if(!maps.available){label(14,80,t("Insert an SD card for maps","Для карты нужна SD-карта"));}
 else if(!maps.haveCenter){label(14,80,t("Load a map via Wi-Fi or USB","Загрузите карту по Wi-Fi или USB"));label(14,103,t("GPS: waiting for position","GPS: ожидание позиции"),muted);}
 else {
  double scale=256UL<<maps.zoom;auto point=[&](double lat,double lon,int& x,int& y){if(!isfinite(lat)||!isfinite(lon)||fabs(lat)>85.05112878)return false;auto yy=[&](double l){double r=l*M_PI/180;return (1-log(tan(r)+1/cos(r))/M_PI)/2*scale;};x=160+int((lon-maps.longitude)/360*scale);y=115+int(yy(lat)-yy(maps.latitude));return x>=8&&x<312&&y>=36&&y<194;};
  for(unsigned i=0;i<meshRadio.peerCount;i++){auto& p=meshRadio.peers[i];int x,y;if(p.position&&point(p.latitude,p.longitude,x,y)){c.fillCircle(x,y,5,0xfaa8);label(constrain(x-30,2,240),y-8,clip(p.name,12),bg);}}
  if(hardware.gpsFix()){int x,y;if(point(hardware.gps.location.lat(),hardware.gps.location.lng(),x,y)){c.fillCircle(x,y,7,white);c.fillCircle(x,y,5,0x047f);}}
  if(!maps.follow){c.drawFastHLine(153,115,15,bg);c.drawFastVLine(160,108,15,bg);}
  c.fillRoundRect(7,33,185,22,4,panel);label(13,48,clip(maps.title.length()?maps.title:t("Offline map","Офлайн-карта"),18),accent);label(145,48,"z"+String(maps.zoom),muted);bool gpsFix=hardware.gpsFix();c.fillRoundRect(200,33,112,22,4,panel);label(207,48,gpsFix?"GPS "+String(hardware.gps.satellites.value())+t(" sat"," спутн."):(hardware.clockConflict?t("GPS: old date","GPS: старая дата"):t("GPS: waiting","GPS: ожидание")),gpsFix?green:muted);
  double metres=cos(maps.latitude*M_PI/180)*40075016.686/scale*60;c.fillRoundRect(229,160,83,32,4,panel);c.drawFastHLine(240,185,60,white);label(237,177,String(int(metres))+" m",white);
  if(!maps.visibleTiles){c.fillRoundRect(8,90,304,40,5,panel);label(16,108,maps.waiting?t("Reading map from SD…","Чтение карты с SD…"):t("This zoom is not downloaded","Этот масштаб не загружен"),muted);if(!maps.waiting)label(16,124,t("Use +/- or L to select a map","Нажмите +/- или L: список карт"),muted);}c.fillRect(0,187,118,15,panel);label(6,199,"© OpenStreetMap",white);
 }
 label(10,216,maps.follow?t("Following GPS","Следовать за GPS"):t("Map browsing","Просмотр карты"),muted);footer(t("Arrows: pan  +/-: zoom  L: maps","Стрелки  +/-: масштаб OK: GPS L: карты"));}
void draw(){auto& c=*hardware.canvas;c.fillScreen(bg);c.fillRect(0,0,320,26,panel);label(9,18,page==Home?"MESHMESH":t("MeshMesh","MeshMesh"),accent);label(113,18,clockText(),muted);label(193,18,meshRadio.ready?"LoRa":"ERR",meshRadio.ready?green:red);label(243,18,hardware.batteryMv?String(hardware.batteryMv/1000.f,2)+" V":"-- V",muted);
 if(locked){label(113,76,t("Locked","Заблокировано"),accent);label(106,109,clockText(),white);label(69,144,t("Hold OK to unlock","Удерживайте OK для входа"),muted);label(35,176,t("Radio and GPS keep working","Радио и GPS продолжают работать"),muted);footer(t("Hold OK · MIC locks the screen","Удерживать OK · MIC: блокировка"));hardware.flush();return;}
 switch(page){
 case Home:{String names[]={t("Chats","Чаты"),t("Map","Карта"),t("Nodes","Узлы"),t("Settings","Настройки"),t("Connect","Подключение")};String details[]={String(meshRadio.historyCount)+t(" messages"," сообщений"),maps.tileCount?maps.title:t("Load offline maps","Загрузить офлайн-карты"),String(meshRadio.peerCount)+t(" discovered"," обнаружено"),t("Radio, screen, modules","Радио, экран, модули"),t("Wi-Fi and Bluetooth","Wi-Fi и Bluetooth")};for(int i=0;i<5;i++)row(49+i*34,names[i],details[i],selected==i);footer(t("MSG: chats  MAP: map  MIC: lock","MSG: чаты  MAP: карта  MIC: блокировка"));break;}
 case Threads:{threads();label(12,45,t("Chats · OK to open","Чаты · OK: открыть"),accent);if(selected>=int(conversationCount))selected=conversationCount-1;unsigned first=selected>3?selected-3:0;for(unsigned i=first;i<conversationCount&&i<first+4;i++){String preview=t("No messages yet","Сообщений ещё нет");for(int j=meshRadio.historyCount-1;j>=0;j--)if(belongs(meshRadio.history[j],conversations[i])){preview=(meshRadio.history[j].outgoing?t("You: ","Вы: "):String(meshRadio.history[j].name)+": ")+meshRadio.history[j].text;break;}unsigned n=unread(conversations[i]);row(70+(i-first)*37,nameOf(conversations[i])+(n?"  +"+String(n):""),clip(preview,44),selected==int(i));}footer(t("ADV: discover nodes  HOME: menu","ADV: найти узлы  HOME: меню"));break;}
 case Chat:drawChat();break;
 case Map:drawMap();break;
 case Library:{label(12,45,t("Saved maps","Сохранённые карты"),accent);unsigned count=library.size();if(!count)label(12,90,t("Upload a map via Wi-Fi","Загрузите карту по Wi-Fi"),muted);int first=selected>3?selected-3:0;for(unsigned i=first;i<count&&i<unsigned(first+4);i++)row(70+(i-first)*37,library[i]["name"].as<String>(),String(library[i]["tiles"].as<unsigned>())+t(" tiles on SD"," тайлов на SD"),selected==int(i));footer(t("OK: open  BACK: map","OK: открыть  BACK: карта"));break;}
 case Nodes:{label(12,45,t("Nodes · OK: personal chat","Узлы · OK: личный чат"),accent);if(!meshRadio.peerCount){label(16,87,t("No nearby nodes yet","Пока нет обнаруженных узлов"));label(16,112,t("ADV sends your announcement","ADV отправляет объявление"),muted);}unsigned first=selected>3?selected-3:0;for(unsigned i=first;i<meshRadio.peerCount&&i<first+4;i++){auto& p=meshRadio.peers[i];row(70+(i-first)*37,p.name,(p.heard?String(int(p.rssi))+" dBm · "+String((millis()-p.seen)/1000)+t("s ago"," сек назад"):t("Saved contact","Сохранённый контакт"))+(p.position?t(" · GPS"," · GPS"):""),selected==int(i));}footer(t("OK: chat  P: show on map","OK: чат  P: показать на карте"));break;}
 case Sensors:{label(12,45,t("GPS & compass","GPS и компас"),accent);bool fix=hardware.gpsFix();label(12,67,"GPS: "+flag(config.gps)+" · "+String(hardware.gps.satellites.value())+t(" satellites"," спутников"),fix?green:muted);label(12,87,fix?String(hardware.gps.location.lat(),5)+", "+String(hardware.gps.location.lng(),5):(hardware.clockConflict?t("GPS date is outdated","GPS: устаревшая дата"):t("Waiting for GPS outdoors","Ожидание GPS под открытым небом")));label(12,107,navigation.headingValid?t("Magnetic north: ","Магнитный азимут: ")+String(navigation.heading,0)+"°":t("Compass: calibrate, hold flat","Компас: калибровка, держать ровно"),muted);row(134,t("Share position","Передать позицию"),t("Send your GPS to the network","Отправить GPS узлам сети"),selected==0);row(169,navigation.calibrating?t("Finish calibration","Завершить калибровку"):t("Calibrate compass","Калибровать компас"),navigation.calibrating?String(navigation.samples)+t(" samples · rotate device"," отсчётов · вращайте устройство"):t("Rotate in all directions ≥20 sec","Вращайте во все стороны ≥20 сек"),selected==1);label(12,209,"IMU "+flag(hardware.imuSample)+" · RTC "+flag(hardware.rtcValid)+" · SD "+flag(hardware.sdOk),muted);footer(t("OK: select  BACK: settings","OK: выбрать  BACK: настройки"));break;}
 case Settings:{String titles[]={t("Radio","Радио"),t("Screen & device","Экран и устройство"),t("GPS & compass","GPS и компас"),t("Connections","Подключения"),t("Module health","Состояние модулей"),t("Help","Как пользоваться")};int first=selected>3?selected-3:0;for(int i=first;i<6&&i<first+4;i++)row(54+(i-first)*39,titles[i],"",selected==i);footer(t("OK: open  BACK: menu","OK: открыть  BACK: меню"));break;}
 case Radio:case Display:{label(12,45,page==Radio?t("Radio settings","Настройки радио"):t("Screen & device","Экран и устройство"),accent);int first=selected>6?selected-6:0;for(int i=first;i<(page==Radio?8:9)&&i<first+7;i++){int y=65+(i-first)*21;if(selected==i)c.fillRoundRect(7,y-14,306,20,4,0x1a69);label(13,y,clip(setting(i),46),selected==i?accent:white);}footer(t("LEFT/RIGHT: change  OK: select/save","Влево/вправо: изменить  OK: выбрать/сохранить"));break;}
 case Network:{label(12,45,t("Connections","Подключение"),accent);for(int i=0;i<3;i++){int y=65+i*22;if(selected==i)c.fillRoundRect(7,y-14,306,20,4,0x1a69);label(13,y,i==0?"Wi-Fi: "+flag(portalActive()):i==1?"Bluetooth: "+flag(bleActive()):String("MeshCore · Public"),selected==i?accent:white);}if(portalActive()){label(13,138,"MM-"+meshRadio.idText(meshRadio.nodeId).substring(6),accent);label(13,158,t("Password: ","Пароль: ")+portalPassword());label(13,178,"192.168.4.1 · meshmesh",muted);}if(bleActive())label(13,204,"BLE PIN: "+String(blePin()),accent);footer(t("OK: toggle  BACK: menu","OK: переключить  BACK: меню"));break;}
 case Diagnostics:{label(12,45,t("Module health","Состояние модулей"),accent);String names[]={"LoRa","Keyboard","SD","LittleFS","RTC","GPS / NMEA","Compass","IMU"};bool ok[]={meshRadio.ready,hardware.keyboardOk,hardware.sdOk,hardware.fsOk,hardware.rtcValid,hardware.gps.passedChecksum()>0,hardware.compassSample,hardware.imuSample};for(int i=0;i<8;i++){label(14,65+i*18,names[i],muted);label(190,65+i*18,ok[i]?t("Working","Работает"):t("Unavailable","Недоступен"),ok[i]?green:red);}label(12,216,"RX "+String(meshRadio.rxCount)+" · TX "+String(meshRadio.txCount)+" · RAM "+String(ESP.getFreeHeap()/1024)+"K",muted);footer(t("OK: crypto test + sound","OK: проверка шифрования и звука"));break;}
 case Help:{String help[]={t("MSG opens your chats","MSG открывает список чатов"),t("Choose node > OK: private chat","Узлы > OK: личный чат"),t("Chat: type > OK to send","Чат: текст > OK для отправки"),t("@ changes EN/RU input","@ меняет EN/RU ввод"),t("MAP: map, +/-: zoom, OK: GPS","MAP: карта, +/-: масштаб, OK: GPS"),t("Wi-Fi: upload maps in browser","Wi-Fi: загрузка карт в браузере"),t("MIC locks; hold OK unlocks","MIC: блокировка; держать OK: вход"),t("Delivered means ACK received","Доставлено = получено подтверждение"),t("HOME: menu; BACK: previous","HOME: меню; BACK: назад")};for(int i=0;i<9;i++)label(10,51+i*18,help[i],i%2?muted:white);footer(t("BACK: settings","BACK: настройки"));break;}
 }
 if(editing){c.fillRoundRect(5,69,310,145,7,panel);label(13,90,page==Network?t("Network key · 64 hex","Ключ сети · 64 hex"):t("Device name","Имя устройства"),accent);String rows[4];unsigned n=lines(edit,rows,45,4);for(unsigned i=0;i<n;i++)label(13,112+i*16,rows[i]);label(13,204,t("OK: save  BACK: cancel","OK: сохранить  BACK: отменить"),muted);}
 if(toast.length()&&millis()-toastAt<3500){c.fillRoundRect(6,197,308,23,4,0x2948);label(12,213,clip(toast,48),accent);}hardware.flush();}
}
void uiBegin(){Preferences p;keyboardRussian=config.russian;if(p.begin("meshmesh-ui",true)){keyboardRussian=p.getBool("kb_ru",config.russian);p.end();}lastInput=millis();draw();}
String uiStatus(){StaticJsonDocument<768>d;d["page"]=pageNames[page];d["locked"]=locked;d["selected"]=selected;d["recipient"]=recipient==meshmesh::Broadcast?"ALL":meshRadio.idText(recipient);d["composer"]=composer;d["composer_bytes"]=composer.length();d["keyboard_language"]=keyboardRussian?"RU":"EN";d["editing"]=editing;d["chat_offset"]=chatOffset;d["idle_seconds"]=(millis()-lastInput)/1000;String s;serializeJson(d,s);return s;}
void uiKey(int key){bool asleep=wakeOnly;lastInput=millis();hardware.brightness(config.brightness);wakeOnly=false;dirty=true;if(locked){if(key==0xa3)locked=false;return;}if(asleep)return;
 if(key==0x88){locked=true;return;}
 if(key==0x83&&(page==Chat||(page==Display&&editing))){keyboardRussian=!keyboardRussian;Preferences p;if(p.begin("meshmesh-ui",false)){p.putBool("kb_ru",keyboardRussian);p.end();}return;}
 if(editing){if(key==0x86){editing=false;return;}if(key==8){edit.remove(meshmesh::previousCharacter(edit.c_str(),edit.length()));return;}if(key==13){if(page==Network){StaticJsonDocument<128>d;d["key"]=edit;String r=applySettings(d.as<JsonObjectConst>());if(r.startsWith("OK"))editing=false;notice(r);}else if(edit.length()&&edit.length()<=24&&meshmesh::validUtf8((const uint8_t*)edit.c_str(),edit.length())){strlcpy(draft.name,edit.c_str(),sizeof draft.name);editing=false;}else notice(t("Name: 1–24 UTF-8 bytes","Имя: 1–24 байта UTF-8"));return;}if(key>=32&&key<127){String ch=page==Network?String(char(key)):keyboard(key);if(edit.length()+ch.length()<=(page==Network?64:24))edit+=ch;}return;}
 if(key==0x82){change(Home);return;}if(key==0x81){change(Threads);return;}if(key==0x85){change(Map);return;}if(key==0x90){change(Settings);return;}if(key==0x84){notice(meshRadio.sendHello()?t("Node announced","Узел объявлен"):t("Announcement failed","Не удалось объявить узел"));return;}
 if(key==0x87){config.gps=!config.gps;config.save();hardware.setGps(config.gps);notice("GPS: "+flag(config.gps));return;}
 if(key==0x86){change(page==Library?Map:page==Chat?chatReturn:(page==Radio||page==Display||page==Sensors||page==Diagnostics||page==Help)?Settings:Home);return;}
 if(key==0x83){change(Diagnostics);return;}
 if(page==Chat){if(key==13){if(meshRadio.sendMessage(composer,recipient)){composer="";chatOffset=0;notice(t("Message queued","Сообщение в очереди"));}else notice(t("Cannot send: empty, full queue or radio","Не отправлено: текст, очередь или радио"));return;}if(key==8){composer.remove(meshmesh::previousCharacter(composer.c_str(),composer.length()));return;}if(key==0xb5){unsigned count=0;for(unsigned i=0;i<meshRadio.historyCount;i++)if(belongs(meshRadio.history[i],recipient))count++;chatOffset=min(chatOffset+1,max(0,int(count)-1));return;}if(key==0xb6){chatOffset=max(0,chatOffset-1);return;}if(key>=32&&key<127){String ch=keyboard(key);if(composer.length()+ch.length()<=meshRadio.messageLimit(recipient))composer+=ch;else notice(t("UTF-8 byte limit: ","Лимит байт UTF-8: ")+String(meshRadio.messageLimit(recipient)));}return;}
 if(page==Map){if(key=='l'||key=='L'){change(Library);return;}if(key==0xb4)maps.pan(-70,0);if(key==0xb7)maps.pan(70,0);if(key==0xb5)maps.pan(0,-70);if(key==0xb6)maps.pan(0,70);if(key=='+'||key=='=')maps.changeZoom(1);if(key=='-'||key=='_')maps.changeZoom(-1);if(key==13){maps.follow=true;if(hardware.gpsFix())maps.center(hardware.gps.location.lat(),hardware.gps.location.lng());else notice(t("Waiting for GPS fix","Ожидание GPS-позиции"));}return;}
 if(page==Nodes&&(key=='p'||key=='P')&&meshRadio.peerCount){auto& p=meshRadio.peers[selected];if(p.position){maps.follow=false;maps.center(p.latitude,p.longitude);change(Map);}else notice(t("This node has not shared GPS","Узел пока не передал GPS"));return;}
 if(key==0xb5||key==0xb6){if(page==Threads)threads();int total=page==Home?5:page==Threads?conversationCount:page==Nodes?meshRadio.peerCount:page==Settings?6:page==Radio?8:page==Display?9:page==Network?3:page==Sensors?2:page==Library?int(library.size()):1;selected=total?(selected+(key==0xb5?-1:1)+total)%total:0;return;}
 if((page==Radio||page==Display)&&(key==0xb4||key==0xb7)){alter(key==0xb4?-1:1);return;}
 if(key!=13&&key!=0xa3)return;
 if(page==Home){Page pages[]={Threads,Map,Nodes,Settings,Network};change(pages[selected]);}
 else if(page==Library&&library.size()){if(maps.selectArea(library[selected]["id"].as<String>()))change(Map);else notice(t("Map unavailable","Карта недоступна"));}
 else if(page==Threads){threads();recipient=conversations[selected];chatReturn=Threads;composer="";change(Chat);}
 else if(page==Nodes&&meshRadio.peerCount){if(meshRadio.peers[selected].type!=1){notice(t("Repeater / server, not a chat node","Ретранслятор / сервер, без личного чата"));return;}recipient=meshRadio.peers[selected].id;chatReturn=Nodes;composer="";change(Chat);}
 else if(page==Settings){Page pages[]={Radio,Display,Sensors,Network,Diagnostics,Help,Library};change(pages[selected]);}
 else if(page==Radio||page==Display){if(selected==(page==Radio?7:8))saveDraft();else if(page==Display&&selected==0){editing=true;edit=draft.name;}else alter(1);}
 else if(page==Network){if(selected==0)portalToggle();if(selected==1)bleToggle();if(selected==2)notice(t("Public key: ","Открытый ключ: ")+meshRadio.publicKeyText().substring(0,16));}
 else if(page==Sensors){if(selected==0)notice(meshRadio.sendPosition()?t("Position shared","Позиция передана"):t("Waiting for GPS fix","Ожидание GPS-позиции"));else if(navigation.calibrating)notice(navigation.finish()?t("Calibration saved","Калибровка сохранена"):t("Rotate wider, at least 20 seconds","Вращайте шире, не менее 20 секунд"));else{navigation.start();notice(t("Rotate in all directions","Вращайте устройство во все стороны"));}}
 else if(page==Diagnostics){hardware.beep();notice(meshRadio.selfTest()?t("Encryption test passed","Проверка шифрования пройдена"):t("Encryption test failed","Ошибка шифрования"));}}
String eventLabel(const String& value){if(!config.russian)return value;if(value.startsWith("New message from "))return "Сообщение от "+value.substring(17);if(value.startsWith("Delivered to "))return "Доставлено: "+value.substring(13);if(value=="Queued: waiting for delivery")return "Ожидание подтверждения";if(value=="Queued: broadcast")return "Сообщение в общем чате отправляется";if(value=="No delivery ACK")return "Получатель не подтвердил доставку";if(value.startsWith("Radio TX error")||value.startsWith("TX failed"))return "Ошибка передачи по радио";return value;}
void uiTick(){uint32_t now=millis();if(config.autoLock&&now-lastInput>=config.autoLock*1000UL&&!locked){locked=true;dirty=true;}if(config.dimAfter&&now-lastInput>=config.dimAfter*1000UL){hardware.brightness(0);wakeOnly=true;}if(meshRadio.event!=eventSeen){eventSeen=meshRadio.event;if(page==Chat){markRead();notice(eventLabel(meshRadio.event));}}if(toast.length()&&now-toastAt>=3500){toast="";dirty=true;}
 bool update=dirty||meshRadio.dirty||maps.dirty||((page==Map||page==Sensors||page==Diagnostics||locked||page==Home)&&now-lastDraw>=1000);if(update&&now-lastDraw>=150){draw();lastDraw=now;dirty=false;meshRadio.dirty=false;maps.dirty=false;}}
