#include "WifiDiagnostics.h"
#include "App.h"
#include <WiFi.h>
#include <HTTPClient.h>
#include <freertos/task.h>
#include <mbedtls/base64.h>
namespace {
bool running=false,done=false;String stage="idle",failure="";bool homepage=false,authRejected=false,apis=false,chunk=false,tile=false,mapSupported=false;unsigned pageBytes=0;portMUX_TYPE guard=portMUX_INITIALIZER_UNLOCKED;
struct Options{char ssid[40],password[64];};
void worker(void* raw){Options* o=(Options*)raw;String auth="meshmesh:"+String(o->password);uint8_t encoded[128];size_t n=0;mbedtls_base64_encode(encoded,sizeof(encoded),&n,(const uint8_t*)auth.c_str(),auth.length());String header="Basic ";header.concat((char*)encoded,n);
 auto fail=[&](const String& value){failure=value;};auto get=[&](const String& path,bool authenticate=true,String body="",bool post=false){HTTPClient http;http.setTimeout(8000);if(!http.begin("http://192.168.4.1"+path)){fail("HTTP init");return String();}if(authenticate)http.addHeader("Authorization",header);int code;if(post){http.addHeader("Content-Type","application/json");code=http.POST(body);}else code=http.GET();String response=http.getString();http.end();if(!authenticate){authRejected=code==401;return response;}if(code!=200)fail("HTTP "+String(code)+" "+response.substring(0,80));return response;};
 // ESP32-S3 Wi-Fi/Bluetooth coexistence requires Wi-Fi modem sleep. Disabling
 // it while BLE is enabled makes the Wi-Fi driver abort during association.
 do{stage="connect";WiFi.mode(WIFI_STA);WiFi.setSleep(true);WiFi.begin(o->ssid,o->password);uint32_t at=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-at<15000)vTaskDelay(pdMS_TO_TICKS(100));if(WiFi.status()!=WL_CONNECTED){fail("Wi-Fi association failed");break;}stage="homepage";String page=get("/");pageBytes=page.length();homepage=page.indexOf("id=\"mapFile\"")>=0&&page.indexOf("id=\"conversations\"")>=0;if(!homepage){fail("New portal page missing");break;}get("/api/config",false);if(!authRejected){fail("Unauthenticated API accepted");break;}stage="apis";apis=true;const char* paths[]={"/api/status","/api/clock","/api/config","/api/messages","/api/nodes","/api/maps","/api/maps/areas","/api/navigation"};DynamicJsonDocument d(24576);for(auto path:paths){String response=get(path);if(failure.length()||deserializeJson(d,response)){apis=false;fail("Invalid API JSON "+String(path));break;}if(!strcmp(path,"/api/maps"))mapSupported=d["available"]|false;}if(!apis)break;if(!mapSupported){stage="done";break;}
 // Diagnostic tile at the world edge cannot replace any user area.
 stage="upload";uint8_t pixels[8]={255,255,0,0,1,0,0,0};uint32_t crc=0xffffffff;for(uint8_t b:pixels){crc^=b;for(int i=0;i<8;i++)crc=(crc>>1)^((crc&1)?0xedb88320:0);}crc^=0xffffffff;
 get("/api/command",true,"{\"command\":\"map cancel\"}",true);String cmd="map begin {\"z\":17,\"x\":0,\"y\":0,\"size\":8,\"crc\":"+String(crc)+"}";d.clear();d["command"]=cmd;String json;serializeJson(d,json);String response=get("/api/command",true,json,true);if(!response.startsWith("OK")){fail(response);break;}
 HTTPClient http;http.setTimeout(8000);http.begin("http://192.168.4.1/api/maps/chunk");http.addHeader("Authorization",header);http.addHeader("Content-Type","application/json");uint8_t mapEncoded[32];size_t mapN=0;mbedtls_base64_encode(mapEncoded,sizeof(mapEncoded),&mapN,pixels,sizeof(pixels));String mapBody="{\"data\":\"";mapBody.concat((char*)mapEncoded,mapN);mapBody+="\"}";int code=http.POST(mapBody);String result=http.getString();http.end();chunk=code==200&&result.startsWith("OK");if(!chunk){fail("Binary map chunk failed "+String(code));break;}
 result=get("/api/command",true,"{\"command\":\"map finish\"}",true);if(!result.startsWith("OK")){fail(result);break;}http.begin("http://192.168.4.1/api/maps/tile?z=17&x=0&y=0");http.addHeader("Authorization",header);code=http.GET();result=http.getString();http.end();tile=code==200&&result.length()==32&&!memcmp(result.c_str(),"MMT1",4)&&!memcmp(result.c_str()+24,pixels,8);if(!tile){fail("Map tile HTTP readback mismatch");break;}stage="done";
 }while(false);
 WiFi.disconnect(true);WiFi.mode(WIFI_OFF);delete o;taskENTER_CRITICAL(&guard);done=true;running=false;taskEXIT_CRITICAL(&guard);vTaskDelete(nullptr);
}
}
bool wifiProbeActive(){taskENTER_CRITICAL(&guard);bool active=running;taskEXIT_CRITICAL(&guard);return active;}
String startWifiProbe(JsonObjectConst values){if(wifiProbeActive()||portalActive())return "ERR Wi-Fi probe busy or portal enabled";if(!values["ssid"].is<const char*>()||!values["password"].is<const char*>())return "ERR Wi-Fi probe credentials";Options* o=new Options{};strlcpy(o->ssid,values["ssid"],sizeof(o->ssid));strlcpy(o->password,values["password"],sizeof(o->password));failure="";stage="starting";homepage=authRejected=apis=chunk=tile=mapSupported=false;pageBytes=0;done=false;running=true;if(xTaskCreate(worker,"wifi-probe",8192,o,1,nullptr)!=pdPASS){delete o;running=false;return "ERR Wi-Fi probe task";}return "OK physical Wi-Fi probe started";}
String wifiProbeResult(){StaticJsonDocument<1024>d;bool active,complete;taskENTER_CRITICAL(&guard);active=running;complete=done;taskEXIT_CRITICAL(&guard);d["running"]=active;d["done"]=complete;d["stage"]=complete?stage:String(active?"running":"idle");if(complete){d["error"]=failure;d["homepage"]=homepage;d["page_bytes"]=pageBytes;d["auth_rejected"]=authRejected;d["apis"]=apis;d["maps_supported"]=mapSupported;d["binary_chunk"]=chunk;d["tile_readback"]=tile;}String s;serializeJson(d,s);return s;}
